sudo: required
language: python
matrix:
    include:
        - python: 3.6
install:
    - sudo apt-get update
    - source ci/travis_install.sh
script:
    - bash ci/travis_test.sh
notifications:
    email:
      recipients:
          - marc.vanoudheusden@gmail.com
    on_success: always
    on_failure: always
