sudo: required
language: python
matrix:
    include:
        - python: 3.5
          env: LATEST="false" COVERAGE="false" NUMPY_VERSION="1.11.2" SCIPY_VERSION="0.18.1" SKLEARN_VERSION="0.18" PANDAS_VERSION="0.19.1"
install:
    - sudo apt-get update
    - source ci/travis_install.sh
script:
    - bash ci/travis_test.sh
after_success:
    - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
notifications:
    email:
      recipients:
          - marc.vanoudheusden@gmail.com
    on_success: always
    on_failure: always
